version: '3.8'

services:
  audiobook_creator:
    build:
      context: ../..
      dockerfile: docker/cpu/Dockerfile
    container_name: audiobook_creator
    volumes:
      - ../..:/app
      - ../../model_cache:/app/model_cache
    depends_on:
      - kokoro_fastapi
    env_file:
      - ../../.env
    restart: always
    network_mode: host

  kokoro_fastapi:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.2  # Use CPU version
    container_name: kokoro_service
    restart: always
    network_mode: host
    command: >
      uvicorn api.src.main:app --host 0.0.0.0 --port 8880 --log-level debug --workers 1